enable: true
resources:
  enabled: true
  bess:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi
images:
  repository: "registry.opennetworking.org/docker.io/"
config:
  upf:
    name: "oaisim"
    sriov:
      enabled: false #default sriov is disabled in AIAB setup
    hugepage:
      enabled: false #should be enabled if dpdk is enabled
    cniPlugin: macvlan
    ipam: static
    enb:
      subnet: "10.10.110.0/24" #this is your gNB network
    access:
      iface: "ens4"
      ip: "192.168.5.10/24" #New IP address for UPF3 access interface
      gateway: "192.168.5.1"
    core:
      iface: "ens4"
      ip: "192.168.6.10/24" #New IP address for UPF3 core interface
      gateway: "192.168.6.1" 
    cfgFiles:
      upf.json:
        mode: af_packet  #this mode means no dpdk
        hwcksum: true
        log_level: "trace"
        gtppsc: false #extension header is enabled in 5G. Sending QFI in pdu session extension header
        enable_notify_bess: false
        measure_upf: false #enable packet processing time
        cpiface:
          dnn: "internet" #keep it matching with Slice dnn
          hostname: "upf"
          #http_port: "8080"
          enable_ue_ip_alloc: false # if true then it means UPF allocates address from below pool
          ue_ip_pool: "172.250.0.0/16" # UE ip pool is used if enable_ue_ip_alloc is set to true
                  # Default global rate limits. Can be changed at runtime via BESS gRPC.
          slice_rate_limit_config:
            # Uplink
            n6_bps: 1000000000 # 1Gbps
            n6_burst_bytes: 12500000 # 10ms * 1Gbps
            # Downlink
            n3_bps: 1000000000 # 1Gbps
            n3_burst_bytes: 12500000 # 10ms * 1Gbps
          qci_qos_config:
            - qci: 0 # Fallback QCI
              cbs: 50000
              ebs: 50000
              pbs: 50000
              burst_duration_ms: 10
              priority: 7

service:
  externalIp: "10.10.1.3" 
