---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: edgeapp1
  namespace: edgeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edgeapp1
  template:
    metadata:
      labels:
        app: edgeapp1
    spec:
      containers:
      - name: edgeservice
        image: docker.io/802dot1q/edgeservice:v2.5
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
        env:
        - name: PYTHONUNBUFFERED
          value: '1'
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: edgeapp1service
  namespace: edgeservice
spec:
  type: NodePort
  selector:
    app: edgeapp1
  ports:
  - port: 6000
    targetPort: 8080
    protocol: UDP
    nodePort: 30002
  externalTrafficPolicy: Local
