# SPDX-FileCopyrightText: 2022-present Intel Corporation
# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

# Override values for omec-user-plane Helm Chart
# https://github.com/omec-project/sdcore-helm-charts/blob/main/bess-upf/values.yaml
nodeSelectors:
  enabled: true
  upf:
    label: site
    value: site1
enable: true
resources:
  enabled: false
images:
  repository: "" # defaults to Docker Hub
  # following two lines pull busybox from Docker Hub instead of Aether Registry
  tags:
    tools: omecproject/busybox:stable
    #  bess: <bess image tag>
    #  pfcpiface: <pfcp image tag>
config:
  upf:
    name: oaisim
    sriov:
      enabled: false # SRIOV is disabled by default
    hugepage:
      enabled: false # Should be enabled if DPDK is enabled
    cniPlugin: macvlan # Can be any other plugin. Dictates how IP address are assigned
    ipam: static
    enb:
      subnet: 10.10.110.0/24 #this is your gNB network
    access:
      iface: ens4
      ip: 192.168.3.20/24 #New IP address for UPF3 access interface
      gateway: 192.168.3.1
    core:
      iface: ens4
      ip: 192.168.4.20/24 #New IP address for UPF3 core interface
      gateway: 192.168.4.1
    cfgFiles:
      upf.jsonc:
        mode: af_packet # This mode implies no DPDK
        hwcksum: true
        log_level: trace
        measure_upf: true
        measure_flow: true
        gtppsc: true # Extension header enabled in 5G.
        cpiface:
          dnn: internet # Must match Slice dnn
          hostname: upf
          #http_port: "8080"
          enable_ue_ip_alloc: false # If true, UPF allocates address from following pool
          ue_ip_pool: 172.250.0.0/16 # IP pool used UEs if enable_ue_ip_alloc=true
        slice_rate_limit_config: # Slice-level rate limiting (also controlled by ROC)
          # Uplink
          n6_bps: 10000000000 # 10Gbps
          n6_burst_bytes: 12500000 # 10ms * 10Gbps
          # Downlink
          n3_bps: 10000000000 # 10Gbps
          n3_burst_bytes: 12500000 # 10ms * 10Gbps
